name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    - name: Build gem
      run: bin/rake install

  docs:
    runs-on: ubuntu-latest
    name: Documentation

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    - name: Build gem
      run: bin/rake docs

  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    - name: Run linters
      run: bin/rake lint

  security:
    runs-on: ubuntu-latest
    name: Security

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    - name: Run security tools
      run: bin/rake security

  test:
    runs-on: ubuntu-latest
    name: Test

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: eve_rails_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    - name: Run the default task
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eve_rails_test
      run: |
        bin/rails db:setup
        bin/rake
